api:
  image: 565273632019.dkr.ecr.us-east-1.amazonaws.com/jobradar-api:56bab1516c79ed7f16bc2de7788e9ff7a868212e
  replicas: 1
  port: 8000
  nodePort: 30080
  imagePullPolicy: Always
  serviceType: ClusterIP

redis:
  image: redis:alpine
  port: 6379