api:
  image: 565273632019.dkr.ecr.us-east-1.amazonaws.com/jobradar-api:c3381b98a67cd42817a01922e9b724b38fcbeaf0
  replicas: 1
  port: 8000
  nodePort: 30080
  imagePullPolicy: Always
  serviceType: ClusterIP

redis:
  image: redis:alpine
  port: 6379