api:
  image: 565273632019.dkr.ecr.us-east-1.amazonaws.com/jobradar-api:a5685141ccef13834fc87df8bb73b4dc9f7d87e9
  replicas: 1
  port: 8000
  nodePort: 30080
  imagePullPolicy: Always
  serviceType: ClusterIP

redis:
  image: redis:alpine
  port: 6379