apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobradar-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: jobradar-api
  template:
    metadata:
      labels:
        app: jobradar-api
    spec:
      containers:
        - name: jobradar-api
          image: {{ .Values.api.image }}
          imagePullPolicy: {{ .Values.api.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jobradar-api
  labels:
    app: jobradar-api
spec:
  selector:
    app: jobradar-api
  type: {{ .Values.api.serviceType }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      nodePort: {{ .Values.api.nodePort }}