apiVersion: v1
kind: Service
metadata:
  name: jobradar-api
  labels:
    app: jobradar-api
spec:
  type: {{ .Values.api.serviceType }}
  selector:
    app: jobradar-api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
